### ISSUE TITLE
All Demos Failing

### ISSUE THREAD

**Issue by Irrelon** [sinisterchipmunk/jax#69] opened 2012-10-18 12:17 UTC
Hey ya!

I was just looking around Jax and tried the demos at http://sinisterchipmunk.github.com/. None of them would load. The JS console shows various errors. On the dungeon one I get: "Error: ERROR: 0:42: '**import_functions_lights**' : macro name is reserved"

On hatching I get: "Error: ERROR: 0:36: '**import_functions_depth_map**' : macro name is reserved"

I'm guessing that is in a shader somewhere. Just thought I'd give you a heads-up as I didn't see any previous issue on the tracker about it.

System:

Win7 64bit
Chrome 22.0.1229.94 m
GeForce GTX 295

**Comment by sinisterchipmunk** [comment] 2012-10-18 13:44
Thanks for the report.

Actually, this bug was discovered while working on Jax 3.0. It seems that some of the naming conventions originally used were always classified "reserved" in the GLSL spec, but only recently starting being enforced by WebGL.

The issue is fixed in Jax 3.0, but without visibility, I'd have forgotten to backport the fix to 2.x, which I'll do sometime this week.

**Comment by Irrelon** [comment] 2012-10-18 13:45
:) awesome. Is Jax 3.0 the latest in the current repo?

**Comment by sinisterchipmunk** [comment] 2012-10-18 13:50
Not sure I understand the question.

The master Git branch is development, and is a little bit further than 3.0, but is also unstable.

The latest officially released version is `2.0.11`, not counting the pre-release version of Jax, `3.0.0.rc1`. (The pre-release version must be explicitly installed with `gem install jax --pre` or by giving its version, `3.0.0.rc1` in the `Gemfile`; otherwise `2.0.11` will be installed by default.)

I'm hoping to push out `3.0.0.rc2`, which contains some bug fixes, sometime this weekend -- but no guarantees, as ever.

FWIW, most of the documentation currently reflects Jax v2.x, and is probably not consistent or correct for 3.x (though the fundamentals still apply).

**Comment by Irrelon** [comment] 2012-10-18 13:52
Ahh ok, thanks! :)

**Comment by sinisterchipmunk** [comment] 2012-10-18 22:10
Looks like I was wrong on one point. This bug is already fixed in Jax v2.x, where I thought it hadn't been. Yay.

Turns out the demos are still running on 2.0.5, which predates the fix for this issue. Upgrading now.

**Comment by sinisterchipmunk** [comment] 2012-10-18 23:08
Demos have been upgraded to use Jax 2.0.12, which was itself just released, and which includes a one-line change that's had a big impact on frame timing. Please see bf225524edb1a1cc9c7c42a3214b0b5b40aa2069 for details.

Please let me know if you continue to encounter issues running the demos.

**Closed as completed by sinisterchipmunk** 2012-10-18 23:08 UTC

**Comment by Irrelon** [comment] 2012-10-21 17:38
Very cool! The demo's all work for me now :) :+1:
